### ISSUE TITLE
Height trigger to fixie nav is thrown off

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#47]
Was working yesterday:

<img width="1229" alt="screen shot 2018-08-14 at 7 38 31 am" src="https://user-images.githubusercontent.com/947791/44092114-1d798b1e-9f95-11e8-8abc-0d785e44b231.png">

**Comment by cjsinner** [comment]
I think this has to do with tthe extra space I tried to put between thhe share buttons and the nav. I'll take it out.

**Comment by cjdd3b** [comment]
Still seeing this:

<img width="1177" alt="screen shot 2018-08-14 at 9 57 04 am" src="https://user-images.githubusercontent.com/947791/44099536-797d217e-9fa8-11e8-88ca-e25cbec0305b.png">

**Comment by cjdd3b** [comment]
Guessing this has to do with variable ad heights and the fact that this is being triggered by `window.pageYOffset`

**Comment by cjdd3b** [comment]
Leaving it in place for now anyway until we have a better idea.

**Comment by zzolo** [comment]
I am not seeing this.

Maybe the JS is breaking?  I am pretty sure, what is happening is that as you scroll back up, the trigger to unstick is not getting fired, and there is a spacer in place of the nav so that there's isn't a big jump when the sticky is fired in the first place.  Since that is not getting fired, I assume something is happening with the JS.  Is there a console error or something?

**Comment by cjsinner** [comment]
ohhhhkayyyyy alan pointed out my weird padding/margin nonsense was creating this problem but IT IS SOLVED NOW I PROMISE.
